import { useState } from "react";


import {
    FiCheckCircle,
    FiArrowRight,
    FiYoutube,
    FiBook,
    FiGithub,
    FiGlobe,
    FiCode,
    FiChevronDown,
    FiChevronUp
} from "react-icons/fi";

function ResourceCard({ icon, title, color, items }) {

    return (

        <div className="
bg-[#111827]/70
rounded-2xl
border
border-white/10
p-5
">

            <div className="flex items-center gap-3 mb-4">

                <div className={color}>
                    {icon}
                </div>

                <h3 className="text-white font-semibold">
                    {title}
                </h3>

            </div>

            <div className="space-y-3">

                {items?.length ? (

                    items.map((item, index) => (

                        <a

                            key={index}

                            href={item.url}

                            target="_blank"

                            rel="noreferrer"

                            className="
block
text-cyan-300
hover:text-white
transition
"

                        >

                            • {item.title}

                        </a>

                    ))

                ) : (

                    <p className="text-gray-500 text-sm">

                        No resources found.

                    </p>

                )}

            </div>

        </div>

    );

}

export default function RoadmapCard({ data }) {

    

    const roadmap = data?.roadmap || [];

    const [openStep, setOpenStep] = useState(null);
    const [completedWeeks, setCompletedWeeks] = useState(
        data?.completed_weeks || {}
    );
    const [loadingProgress, setLoadingProgress] = useState(true);

    useEffect(() => {
        const loadProgress = async () => {
            try {
                const token = localStorage.getItem("token");

                if (!token) {
                    setLoadingProgress(false);
                    return;
                }

                const response = await fetch(
                    "https:///campus-recruitment-predictor.onrender.com/get-roadmap-progress",
                    {
                        method: "GET",
                        headers: {
                            Authorization: `Bearer ${token}`
                        }
                    }
                );

                const result = await response.json();

                if (response.ok) {
                    setCompletedWeeks(result.completedWeeks || {});
                }

            } catch (error) {
                console.error("Failed to load roadmap progress:", error);
            } finally {
                setLoadingProgress(false);
            }
        };

        loadProgress();
    }, []);

    const completedCount = Object.values(completedWeeks).filter(Boolean).length;

    const progress =
        roadmap.length > 0
            ? Math.round((completedCount / roadmap.length) * 100)
            : 0;

    return (

        <div
            className="
relative
overflow-hidden
bg-gradient-to-br
from-[#111827]
via-[#0B1220]
to-[#09111F]
rounded-[30px]
border
border-white/10
p-7
shadow-[0_20px_50px_rgba(0,0,0,0.35)]
transition-all
duration-300
hover:-translate-y-2
hover:border-cyan-400/40
hover:shadow-[0_0_40px_rgba(34,211,238,0.20)]
"
        >

            <div className="absolute top-0 right-0 w-44 h-44 bg-cyan-500/10 rounded-full blur-3xl"></div>

            <div className="absolute bottom-0 left-0 w-36 h-36 bg-blue-500/10 rounded-full blur-3xl"></div>

            <div className="relative z-10">

            </div>

            <div className="flex justify-between items-center mb-8">

                <div>

                    <h2 className="text-3xl font-bold text-white">
                        AI Career Roadmap
                    </h2>

                    <p className="text-gray-400 text-sm mt-1">
                        Personalized learning path generated by AI
                    </p>

                </div>

                <span className="px-4 py-2 rounded-full bg-cyan-500/15 border border-cyan-500/20 text-cyan-300 text-xs font-semibold">

                    {roadmap.length} Steps

                </span>

            </div>

            <div className="space-y-5">

                {roadmap.length > 0 ? (

                    roadmap.map((step, index) => (

                        <div
                            key={index}
                            className="
bg-[#111827]/70
rounded-[24px]
border
border-white/5
overflow-hidden
transition-all
duration-300
hover:border-cyan-400/40
"
                        >

                            <div
                                onClick={() =>
                                    setOpenStep(
                                        openStep === index ? null : index
                                    )
                                }
                                className="
cursor-pointer
flex
justify-between
items-center
p-6
"
                            >

                                <div className="flex gap-4 items-center">

                                    {/* Checkbox */}
                                    <div
                                        onClick={(e) => e.stopPropagation()}
                                        className="flex-shrink-0"
                                    >
                                        <input
                                            type="checkbox"
                                            checked={!!completedWeeks[index]}
                                            
                                            onChange={async (e) => {
                                                const checked = e.target.checked;

                                                const updatedProgress = {
                                                    ...completedWeeks,
                                                    [index]: checked
                                                };

                                                setCompletedWeeks(updatedProgress);

                                                try {
                                                    const token = localStorage.getItem("token");

                                                    console.log("TOKEN:", token);
                                                    console.log("PROGRESS TO SAVE:", updatedProgress);

                                                    const response = await fetch(
                                                        "https:///campus-recruitment-predictor.onrender.com/save-roadmap-progress",
                                                        {
                                                            method: "POST",
                                                            headers: {
                                                                "Content-Type": "application/json",
                                                                "Authorization": `Bearer ${token}`
                                                            },
                                                            body: JSON.stringify({
                                                                completedWeeks: updatedProgress
                                                            })
                                                        }
                                                    );

                                                    console.log("STATUS:", response.status);

                                                    const result = await response.json();

                                                    console.log("SAVE RESPONSE:", result);

                                                    if (!response.ok) {
                                                        console.error("SAVE FAILED:", result);
                                                    }

                                                } catch (error) {
                                                    console.error("FAILED TO SAVE ROADMAP:", error);
                                                }
                                            }}
                                            className="
                w-5
                h-5
                accent-cyan-400
                cursor-pointer
            "
                                        />
                                    </div>

                                    {/* Week Icon */}
                                    <div
                                        className={`
            w-12 h-12
            rounded-2xl
            bg-gradient-to-br
            from-cyan-400
            to-blue-600
            flex
            items-center
            justify-center
            transition-all
            duration-300
            ${completedWeeks[index] ? "opacity-50" : ""}
        `}
                                    >
                                        <FiCheckCircle className="text-black" />
                                    </div>


                                    <div>

                                        <h3 className="text-white font-semibold">

                                            Week {step.week}

                                        </h3>

                                        <p className="text-gray-300">

                                            {step.title}

                                        </p>

                                            <span
                                                className={`text-xs ${completedWeeks[index]
                                                        ? "text-green-400"
                                                        : "text-yellow-300"
                                                    }`}
                                            >
                                                {completedWeeks[index] ? "Completed" : "Pending"}
                                            </span>

                                    </div>

                                </div>

                                {openStep === index ?

                                    <FiChevronUp className="text-cyan-400" />

                                    :

                                    <FiChevronDown className="text-cyan-400" />

                                }

                            </div>

                            {openStep === index && (

                                <div className="px-6 pb-6 space-y-6">

                                    <div>

                                        <h4 className="text-cyan-300 font-semibold mb-2">

                                            Daily Tasks

                                        </h4>

                                        <ul className="list-disc list-inside text-gray-300 space-y-1">

                                            {step.daily_tasks?.map((task, i) => (

                                                <li key={i}>{task}</li>

                                            ))}

                                        </ul>

                                    </div>

                                    <div>

                                        <h4 className="text-cyan-300 font-semibold mb-2">

                                            Mini Project

                                        </h4>

                                        <p className="text-gray-300">

                                            {step.mini_project}

                                        </p>

                                    </div>

                                    <div>

                                        <h4 className="text-cyan-300 font-semibold mb-2">

                                            Interview Topics

                                        </h4>

                                        <div className="flex flex-wrap gap-2">

                                            {step.interview_topics?.map((item, i) => (

                                                <span
                                                    key={i}
                                                    className="px-3 py-1 rounded-full bg-cyan-500/10 text-cyan-300 text-sm"
                                                >

                                                    {item}

                                                </span>

                                            ))}

                                        </div>

                                    </div>

                                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-6">

                                        <ResourceCard
                                            icon={<FiYoutube className="text-red-500 text-xl" />}
                                            title="YouTube (English)"
                                            color=""
                                            items={step.resources?.english_videos || []}
                                        />

                                        <ResourceCard
                                            icon={<FiYoutube className="text-orange-500 text-xl" />}
                                            title="YouTube (Hindi)"
                                            color=""
                                            items={step.resources?.hinglish_videos || []}
                                        />

                                        <ResourceCard
                                            icon={<FiGithub className="text-green-400 text-xl" />}
                                            title="GitHub"
                                            color=""
                                            items={step.resources?.github || []}
                                        />

                                        <ResourceCard
                                            icon={<FiBook className="text-cyan-400 text-xl" />}
                                            title="Documentation"
                                            color=""
                                            items={step.resources?.documentation || []}
                                        />

                                        <ResourceCard
                                            icon={<FiCode className="text-yellow-400 text-xl" />}
                                            title="Practice"
                                            color=""
                                            items={step.resources?.practice || []}
                                        />

                                        <ResourceCard
                                            icon={<FiBook className="text-purple-400 text-xl" />}
                                            title="Books"
                                            color=""
                                            items={step.resources?.books || []}
                                        />

                                    </div>
                                    

                                </div>

                            )}

                        </div>

                    ))

                            ) : (

                            <div className="text-center py-10 text-gray-400">

                                No roadmap generated yet.

                            </div>

)}


                <div className="mt-8 border-t border-white/5 pt-6">

                    <div className="flex justify-between mb-2">

                        <span className="text-gray-400 text-sm">

                            Overall Progress

                        </span>

                        <span className="text-cyan-300 font-semibold">

                                        {progress}%

                        </span>

                    </div>

                    <div className="h-3 rounded-full bg-[#111827] overflow-hidden">

                        <div
                            className="h-full bg-gradient-to-r from-cyan-400 to-blue-500 rounded-full"
                            style={{
                                width: `${progress}%`
                            }}
                        ></div>

                    </div>

                </div>

            </div>

        </div>

    );

}